const quiz_genres = [
  'Football (or Soccer)',
  'Food and Culinary Arts',
  'History',
  'Literature',
  'Science Fiction',
  'Fantasy',
  'Mystery',
  'Romance',
  'Horror',
  'Thriller',
  'Biography',
  'Comedy',
  'Drama',
  'Action and Adventure',
  'Philosophy',
  'Psychology',
  'Politics',
  'Economics',
  'Technology',
  'Environment',
  'Astronomy',
  'Mathematics',
  'Medicine',
  'Art and Design',
  'Music',
  'Film and Cinema',
  'Photography',
  'Travel and Tourism',
  'Religion and Spirituality',
  'Education',
  'Sociology',
  'Anthropology',
  'Mythology',
  'Architecture',
  'Poetry',
  'Self-Help',
  'Business and Entrepreneurship',
  'Personal Finance',
  'Sports (General)',
  'Cricket',
  'Martial Arts',
  'Fitness and Wellness',
  'Video Games',
  'Animation',
  'Fashion',
  'Gardening',
  'Animal Care',
  'Nature and Wildlife',
  'True Crime',
  'Science and Innovation'
];

export default quiz_genres;
